# Generated by Django 3.1.3 on 2020-11-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='directions',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
    ]
