# Generated by Django 3.1.3 on 2020-11-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodme', '0002_auto_20201126_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='directions',
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.CharField(default='Stephen', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default='2 garlic'),
            preserve_default=False,
        ),
    ]
