# Generated by Django 3.1.3 on 2020-11-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodme', '0003_auto_20201126_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='directions',
            field=models.TextField(default='garlic'),
        ),
    ]
