# Generated by Django 3.1.3 on 2020-11-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodme', '0004_auto_20201126_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='directions',
        ),
    ]
