# Generated by Django 3.1.3 on 2020-11-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodme', '0005_auto_20201127_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='directions',
            field=models.TextField(default=' '),
        ),
    ]
